# Generated by Django 4.2.25 on 2025-12-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('exito', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('fch_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
